#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: Claire BUTAYE
"""

import dash 
import dash_bootstrap_components as dbc
from dash import html

# ---- Styles ----------------------------------------------------------------

row_style = {'marginTop': '1%',
             'backgroundColor':'lightgrey'}

card_style = {'height':'100%'}


# ---- Script of the page "Data quality" -------------------------------------

dash.register_page(__name__, 
                   path = '/home/data_quality',
                   external_stylesheets=[dbc.themes.BOOTSTRAP])


# Layout composed of two rows of text
layout = dbc.Container(children = [
    
    dbc.Row (id = 'topRow',
             children = [
                 dbc.Col (dbc.Card(
                                     dbc.CardBody([
                                         html.H2("Data",
                                                 style={'fontSize':'30px', 
                                                        'fontWeight':'lighter'}),
                                         html.Hr(),
                                         html.H6('''The WHO Mortality Database is a 
                                                 compilation of mortality data by 
                                                 country and area, year, sex, age 
                                                 and cause of death, as transmitted 
                                                 annually by national authorities 
                                                 from their civil registration and 
                                                 vital statistics system. It comprises 
                                                 data since 1950 to date.''')
                                         ]),
                                     color = 'white',
                                     style = card_style
                                     ),  
                         width = 12)
                 ],
             style = row_style),

    
    dbc.Row (id = 'middleRow',
             children = [
                 dbc.Col (dbc.Card(
                                     dbc.CardBody([
                                         
                                         html.H2("Warnings about the data collection",
                                                 style={'fontSize':'30px', 
                                                        'fontWeight':'lighter'}),
                                         html.Hr(),
                                    
                                         html.H6('''Users should keep in mind 
                                                 that not all countries report 
                                                 data to the WHO. National death 
                                                 registration statistics with cause 
                                                 of death are generated by a complex, 
                                                 multistep process involving multiple 
                                                 government agencies and hundreds of 
                                                 daily activities.  In many countries,
                                                 particularly in sub-Saharan Africa and
                                                 Asia, these systems have not been 
                                                 institutionalized. Further, medical 
                                                 certification of cause of death requires
                                                 trained personnel, of whom there is a 
                                                 shortage in many of these same countries.'''),
                                                 
                                   
                                    ]),
                                     color = 'white',
                                     style = card_style
                                     ),  
                         width = 12)
                 ],
             style = row_style),
                                            
                                     
    
    ], className  ='vh-100')